title: Essays
email: 123456789@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of GRE writing examples for your reference.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://larry-cui.github.io/jekyll_watery/" # the base hostname & protocol for your site, e.g. http://example.com
repository:
twitter:
github: https://github.com/Larry-Cui

google_analytics:
comments: false
disqus: watery-jekyll

author: Anonymous
author_pic: /img/husky_dog.jpeg
author_bio: >-

paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
