title: Larry's Blog 🌊
email: 811975918@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  math, code and fun
baseurl: "" # the subpath of your site, e.g. /blog
url: "larry-cui.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository:
twitter:
github: Larry-Cui

google_analytics:
comments: false
disqus: watery-jekyll

author: Larry Cui
author_pic: /img/husky_dog.jpeg
author_bio: >-
  A greenhorn coder and a big fan of math.

paginate: 10
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

theme_switcher: false

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
